# Generated by Django 4.1 on 2023-09-27 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner_location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerlocation",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
