# Generated by Django 4.1 on 2023-09-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="imagens",
            field=models.ImageField(blank=True, null=True, upload_to="local/imagens/"),
        ),
    ]
