# Generated by Django 4.2.4 on 2023-09-10 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partner_location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bike_count", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit Card"),
                            ("DEBIT", "Debit Card"),
                            ("CASH", "Cash"),
                            ("PIX", "Pix"),
                        ],
                        default="CREDIT",
                        max_length=10,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="partner_location.partnerlocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
